#+title: Fish Shell Config
#+author: David Basile Filho
#+startup: showeverything
#+description: An org document for David Basile Filho's Fish Shell Config file
#+property: header-args :tangle config.fish
#+auto_tangle: t

* TABLE OF CONTENTS :toc:
- [[#fish-shell][FISH SHELL]]
- [[#aliases][ALIASES]]
- [[#default][DEFAULT]]
- [[#path][PATH]]
- [[#no-greeting-message][NO GREETING MESSAGE]]
- [[#starship-prompt][STARSHIP PROMPT]]
- [[#fun-programs][FUN PROGRAMS]]

* FISH SHELL
The friendly interactive shell is a Unix shell that attempts to be more interactive and user-friendly than those with a longer history or those formulated as function-compatible replacements for the aforementioned. The design goal of fish is to give the user a rich set of powerful features in a way that is easy to discover, remember, and use.

* ALIASES
Some aliases I created for commands I use quite a bit.

#+begin_src shell
alias ..='cd ..'
alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias ls='exa -la'
alias em='emacs -nw'
#+end_src

* DEFAULT
Sets some default environment variables that are not PATH.

#+begin_src shell
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib64"
#+end_src

* PATH
Adds some paths to the PATH environment variable.

#+begin_src shell
export PATH="$HOME/.emacs.d/bin:$PATH"
export PATH="$HOME/.config:$PATH"
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.dotfiles/bin:$PATH"
#+end_src

* NO GREETING MESSAGE
Gets rid of the fish shell's annoying greeting message.

#+begin_src shell
set -U fish_greeting
#+end_src

* STARSHIP PROMPT
Sets up the Starship prompt and runs fastfetch.

#+begin_src shell
starship init fish | source
#+end_src

* FUN PROGRAMS
Runs some cool programs like fastfetch.

#+begin_src shell
fastfetch
#+end_src
